### PR TITLE
Specify options.addMeta to have metadata object appended to all logs

### PR DESCRIPTION
**Pull request by martin-wintz**

### CODE REVIEW

**Comment by Trindaz** [comment]
Is this fork really necessary? It looks like `meta` is already supported on the console and file transports, so why don't we just extend those in the CMC and wrap calls to log that inject meta data?

**Comment by martin-wintz** [comment]
@Trindaz it's really just to support it for exceptions, where wrapping does not work.

It is possible to do this by monkey patching and not forking. Actually, @dsharkey was in favor of monkey patching. I think there are different trade-offs to doing one or the other and it's hard to make a clear cut decision. If forking turns out to be a problem when we upgrade Winston, we can easily turn this into a monkeypatch since it's such a simple change anyway.

**Comment by Trindaz** [comment]
I was just refreshing my memory on various strategies for this here > http://me.dt.in.th/page/JavaScript-override/ and also by checking https://lodash.com/docs#wrap. But if these are all a bit too tricky then we could just create a class that provides a similar interface it could maintain it's own reference to the winston transporters and handle transforming arguments that way.

My main problem is the nature of the forks we're making. They're not really adding a missing feature to the repos and they're fundamentally necessary in the same way I think the `mongoose` fork was. So I think this is just suboptimal, but not a huge crime. If you really don't want to use some form of monkey patching / new class creation then I guess we can just proceed.

**Comment by Trindaz** [comment]
@raficus I think my account might not have the permissions required to merge this.

```
ERROR: Permission to newscred/winston.git denied to Trindaz.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Pull request merged**
